### PR TITLE
April public comment resolution

### PR DESCRIPTION
**Pull request by kinsonho**
Addressed all public comments.

### CODE REVIEW

**Comment by kinsonho** [comment]
All changed reviewed by committee.

**Comment by lynnfel** [comment]
Completing review to enable merge of this PR to master

**Review by lynnfel — COMMENTED** [review]
reviewed

**Comment by lynnfel** [comment]
didn't meant to close.   Wanted to approve PR to merge this branch into master.

**Review by lynnfel — APPROVED** [review]
Reviewed and Approved.

**Pull request merged**
